server:
  port: 9411

cloudant:
  url: http://localhost:5984

logging:
  level:
    com.clianz.zipkin: DEBUG

spring:
  application:
    # This ends up as the service name in zipkin
    name: zipkin
#  zipkin:
#    # Uncomment to send to zipkin, replacing 192.168.99.100 with your zipkin IP address
#     baseUrl: http://127.0.0.1:9411/
#  sleuth:
#    sampler:
#      percentage: 1.0
#
#sample:
#  zipkin:
#    # When enabled=false, traces log to the console. Comment to send to zipkin
##    enabled: false